schema_version = "1.0.0"
id = "rk_importer"
version = "1.2.0"
name = "RK Importer"
tagline = "Extension for importing .rk files from mlp"
maintainer = "ego-lay-atman-bay"
type = "add-on"

# Optional link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

tags = ["Import-Export"]
blender_version_min = "5.1.0"

license = ["SPDX:GPL-3.0-or-later"]

platforms = ["windows-x64", "macos-arm64", "linux-x64"]

# dependencies = 'local-dependencies.txt' # Local dev dependencies
dependencies = 'dependencies.txt'
wheel-path = './wheels'

[permissions]
files = "Import RK files from disk"

[build]
source = './src'
build = './build'
dist = './dist'
output-filepath = '{id}-{version}.zip'
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/.venv/",
  ".gitignore",
  ".gitattributes",
]
paths = [
  'LICENSE',
  'README.md',
]
